### register
POST http://localhost:3000/api/auth/login
Content-Type: application/json

    {
    "email": "zhafran@example.com",
    "password": "123456"
    }

### register
GET http://localhost:3000/api/auth/getAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJuYW1lIjoiemhhZnJhbiIsImVtYWlsIjoiemhhZnJhbkBleGFtcGxlLmNvbSIsImlhdCI6MTc0NzkyODg3MywiZXhwIjoxNzQ3OTI4ODkzfQ.g9fLYAW0FBM3Rll_534du2YScKtVZyDo7q-GedqObRs


### get token
GET http://localhost:3000/api/auth/token

### logout
DELETE http://localhost:3000/api/auth/logout
Authorization: Bearer .eyJ1c2VySWQiOjQsInVzZXJuYW1lIjoiemhhZnJhbiIsImVtYWlsIjoiemhhZnJhbkBleGFtcGxlLmNvbSIsImlhdCI6MTc0NzkyODU1OSwiZXhwIjoxNzQ3OTI4NTc0fQ.qecY4gkUv5-pxGtuBZqA2msN9R0vKoYyW8PVAZ-G-yk
